%%%------------------------------------------------------------------------------------%%
%%%------------------------------------------------------------------------------------%%
%%% Content: Open-Science-Thesis LaTeX Scaffold 
%%% Usage: Collaborative scientific thesis writing 
%%% Author: Claas-Thido Pfaff
%%%------------------------------------------------------------------------------------%%
%%%------------------------------------------------------------------------------------%%

%%%------------------------------------------------------------------------------%%%
%%% Document class: open_science_thesis (Based on Koma-Script: article) %%%
%%%------------------------------------------------------------------------------%%%
%%
%

\documentclass[color = false, autolayout = false, DIV=10]{ost/subdocuments/open_science_thesis} 

%% Available class options [defaults]
% - color true/[false]: Changes between colored output and a black and white theme (needs some work to setup all the headers with their right colors)

% - gitinfo true/[false]: Include git information into the title header of the 
%   document. This requires the setup of git hooks which you can do by issuing 
%   the make task (make githooks). After that you need to specify the url of the 
%   git repository inside of the style file and you are done.  (needs some work)

% - print true/[false] switches between the color model rgb which is optimal for displays 
%   and the cmyk color model which is required for professional printing. 
% - linenumbers true/[false]: Switch on/off line numbers for the whole document. 

% - sectionnumbers true/[false]: Switch between numbered and numberless sections  (needs some work)

% - autolayout [true]/false: Switch between the nice automatic calculated typearea layout 
%   (Koma script) and a fixed geometry page layout (geometry package). You need to set the 
%   geometry inside of the style file if you choose false. (needs some work)

% - twosidelayout true/[false]: Switch between two and one side page layout. (remove?) 

% - reversepagelayout [false]/true reverse the order of odd and even side margins. This 
%   option can be used to start the thesis on a left or right page.  (remove?) 

% - resetdefaultclassoptions true/[false] resets the default options the open science thesis 
%   loads the scrartcl class. After that you can modify every option via the open science 
%   thesis class call. For example to change the calculated typearea you can use 
%   \documentclass[resetdefaultclassoptions=true, DIV=7]{ost/subdocuments/open_science_thesis}   

% - parindent true/[false] Switch paragraph indent on or off.

%%%------------------------------------------------------------------------------%%%
%%% Load user options %%%
%%%------------------------------------------------------------------------------%%%

\input{usr/subdocuments/options/ost_document_options.sty} 

%%%------------------------------------------------------------------------------%%%
%%% Load glossary definitions %%%
%%%------------------------------------------------------------------------------%%%

<<glossary_definitions, child='usr/subdocuments/options/open_science_glossary.Rnw', eval=TRUE>>=
@

%%%------------------------------------------------------------------------------%%%
%%% Begin the document %%%
%%%------------------------------------------------------------------------------%%%


\begin{document}

\frontmatter
%%%--------------------------------------------------------------%%%
%%% Document preparations %%%
%%%--------------------------------------------------------------%%%
%%
%

%%%-------------------------------------------------%%%
%%% Preferences for Knitr %%%
%%%-------------------------------------------------%%%

<<chunk_global_r_options, child='usr/subdocuments/options/ost_global_r_options.Rnw', eval=TRUE>>=
@ 

%%%--------------------------------------------------------------%%%
%%% Document content %%%
%%%--------------------------------------------------------------%%%
%%
%

%%%-------------------------------------------------%%%
%%% Include header %%%
%%%-------------------------------------------------%%%

<<subdoc_content_header, child='usr/subdocuments/chapters/ost_header.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Tables of content %%%
%%%-------------------------------------------------%%%

\tableofcontents
\listoffigures 
\listoftables 

%%%-------------------------------------------------%%%
%%% Affidavit %%%
%%%-------------------------------------------------%%%
\mainmatter
<<subdoc_content_introduction, child='usr/subdocuments/chapters/ost_affidavit_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include abstract %%%
%%%-------------------------------------------------%%%

<<subdoc_content_abstract, child='usr/subdocuments/chapters/ost_abstract_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include introduction %%%
%%%-------------------------------------------------%%%

<<subdoc_content_introduction, child='usr/subdocuments/chapters/ost_introduction_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include material and methods %%%
%%%-------------------------------------------------%%%

<<subdoc_content_material_methods, child='usr/subdocuments/chapters/ost_material_methods_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include results %%%
%%%-------------------------------------------------%%%

<<subdoc_content_results, child='usr/subdocuments/chapters/ost_results_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include discussion %%%
%%%-------------------------------------------------%%%

<<subdoc_content_discussion, child='usr/subdocuments/chapters/ost_discussion_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include acknowledgements %%%
%%%-------------------------------------------------%%%

<<subdoc_content_acknowledgement, child='usr/subdocuments/chapters/ost_acknowledgements_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include the appendix %%%
%%%-------------------------------------------------%%%

% \begin{ostAppendix} 
<<subdoc_content_appendix, child='usr/subdocuments/chapters/ost_appendix_section.Rnw', eval=T>>=
@ 
% \end{ostAppendix} 
\backmatter
%%%-------------------------------------------------%%%
%%% Glossary %%%
%%%-------------------------------------------------%%%

% <<body_mainmatter_chapter_one, child='usr/subdocuments/chapters/ost_glossaries_section.Rnw', eval=TRUE>>=
% @

%%%-------------------------------------------------%%%
%%% Include the bibliography %%%
%%%-------------------------------------------------%%%

<<options_bibliography, child='usr/subdocuments/chapters/ost_bibliography_section.Rnw', eval=T>>=
@


%%%------------------------------------------------------------------------------%%%
%%% End of document %%%
%%%------------------------------------------------------------------------------%%%

\end{document}
