%%%------------------------------------------------------------------------------------%%
%%%------------------------------------------------------------------------------------%%
%%% Content: Open-Science-Thesis LaTeX Scaffold 
%%% Usage: Collaborative scientific document writing 
%%% Author: Claas-Thido Pfaff
%%%------------------------------------------------------------------------------------%%
%%%------------------------------------------------------------------------------------%%

%%%------------------------------------------------------------------------------%%%
%%% Document class: open_science_thesis (Based on Koma-Script: article) %%%
%%%------------------------------------------------------------------------------%%%
%%
%

\documentclass[linenumbers=false, color=false]{ost/subdocuments/open_science_thesis} 

%% Available class options [defaults]
% - color true/[false]: Changes between colored output and a black and white theme 
% - gitinfo true/[false]: Include git information into the title header of the 
%   document. This requires the setup of git hooks which you can do by issuing 
%   the make task (make githooks). After that you need to specify the url of the 
%   git repository inside of the style file and you are done.
% - print true/[false] switches between the color model rgb which is optimal for displays 
%   and the cmyk color model which is required for professional printing. 
% - linenumbers true/[false]: Switch on/off line numbers for the whole document.
% - autolayout [true]/false: Switch between the nice automatic calculated typearea layout 
%   (Koma script) and a fixed geometry page layout (geometry package). You need to set the 
%   geometry inside of the style file if you choose false. 
% - twosidelayout true/[false]: Switch between two and one side page layout.
% - reversepagelayout [false]/true reverse the order of odd and even side margins. This 
%   option can be used to start the paper on a left or right page. 
% - resetdefaultclassoptions true/[false] resets the default options the open science paper 
%   loads the scrartcl class. After that you can modify every option via the open science 
%   paper class call. For example to change the calculated typearea you can use 
%   \documentclass[resetdefaultclassoptions=true, DIV=7]{ost/subdocuments/open_science_paper}  
% - parindent true/[false] Switch paragraph indent on or off.

%%%------------------------------------------------------------------------------%%%
%%% Load user options %%%
%%%------------------------------------------------------------------------------%%%

\input{usr/subdocuments/open_science_thesis.sty} 

%%%------------------------------------------------------------------------------%%%
%%% Begin the document %%%
%%%------------------------------------------------------------------------------%%%

\begin{document}

%%%--------------------------------------------------------------%%%
%%% Document preparations %%%
%%%--------------------------------------------------------------%%%
%%
% 

%%%-------------------------------------------------%%%
%%% Preferences for Knitr %%%
%%%-------------------------------------------------%%%

<<global_knitr_options, child='usr/subdocuments/ost_global_knitr_options.Rnw', eval=TRUE>>=
@

%%%--------------------------------------------------------------%%%
%%% Document content %%%
%%%--------------------------------------------------------------%%%
%%
%

%%%-------------------------------------------------------%%%
%%% Front matter %%%
%%%-------------------------------------------------------%%%
%%
%

%%%-------------------------------------------------%%%
%%% Include title %%%
%%%-------------------------------------------------%%%

<<subdoc_content_titlepage, child='usr/subdocuments/ost_titlepage.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Tables of content %%%
%%%-------------------------------------------------%%%

\tableofcontents
\listoffigures 
\listoftables 

%%%-------------------------------------------------%%%
%%% Include introduction %%%
%%%-------------------------------------------------%%%

<<subdoc_content_introduction, child='usr/subdocuments/ost_introduction_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Affidavit %%%
%%%-------------------------------------------------%%%

<<subdoc_content_introduction, child='usr/subdocuments/ost_affidavit_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------------%%%
%%% Main matter %%%
%%%-------------------------------------------------------%%%
%%
%

%%%-------------------------------------------------%%%
%%% Include material and methods %%%
%%%-------------------------------------------------%%%

<<subdoc_content_material_methods, child='usr/subdocuments/ost_material_methods_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include results %%%
%%%-------------------------------------------------%%%

<<subdoc_content_results, child='usr/subdocuments/ost_results_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include discussion %%%
%%%-------------------------------------------------%%%

<<subdoc_content_discussion, child='usr/subdocuments/ost_discussion_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------------%%%
%%% Back matter %%%
%%%-------------------------------------------------------%%%
%%
%

%%%-------------------------------------------------%%%
%%% Include acknowledgements %%%
%%%-------------------------------------------------%%%

<<subdoc_content_acknowledgement, child='usr/subdocuments/ost_acknowledgements_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Appendix %%%
%%%-------------------------------------------------%%%

<<body_mainmatter_chapter_one, child='usr/subdocuments/ost_appendix_section.Rnw', eval=TRUE>>=
@

%%%-------------------------------------------------%%%
%%% Glossary %%%
%%%-------------------------------------------------%%%

<<body_mainmatter_chapter_one, child='usr/subdocuments/ost_glossaries_section.Rnw', eval=TRUE>>=
@

%%%-------------------------------------------------%%%
%%% Include the bibliography %%%
%%%-------------------------------------------------%%%

<<options_bibliography, child='usr/subdocuments/ost_bibliography_section.Rnw', eval=T>>=
@

%%%------------------------------------------------------------------------------%%%
%%% End of document %%%
%%%------------------------------------------------------------------------------%%%

\end{document}
