%%%-------------------------------------------------%%%
%%% Sub document affidavit %%%
%%%-------------------------------------------------%%% 

I hereby declare that this thesis has been written only by the undersigned and
without any assistance from third parties. Furthermore, I confirm that no
sources have been used in the preparation of this thesis other than those
indicated in the thesis itself. 

Date, Location, Signature

