%%%-------------------------------------------------%%%
%%% Sub document affidavit %%%
%%%-------------------------------------------------%%% 

% \part{Preface}

\chapter{Affidavit} 

I hereby declare that this document has been written only by the undersigned
and without any assistance from third parties. Furthermore, I confirm that no
sources have been used in the preparation of this document other than those
indicated in the thesis itself. 

\ostAffidavitSignatureLine{}
